<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.6.42">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>algonquin-land-claim-investigation – GenAI for Historians: A Practical Introduction</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-2f5df379a58b258e96c21c0638c20c03.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-5cee4c14d6ae2ae54d05c3ac90f01e34.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="./index.html">
    <span class="navbar-title">GenAI for Historians: A Practical Introduction</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="./index.html"> 
<span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./what-are-llms.html"> 
<span class="menu-text">What Are LLMs?</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./getting-started.html"> 
<span class="menu-text">Getting Started</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./research-tasks.html"> 
<span class="menu-text">Research Tasks</span></a>
  </li>  
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-deep-research" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Deep Research</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-deep-research">    
        <li>
    <a class="dropdown-item" href="./deep-research.html">
 <span class="dropdown-text">Deep Research Tools</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./deep-research-example.html">
 <span class="dropdown-text">Example: Marine Insurance</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./deep-research-algonquin.html">
 <span class="dropdown-text">Example: Algonquin Land Claim</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="./case-studies.html"> 
<span class="menu-text">Case Studies</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./teaching.html"> 
<span class="menu-text">Teaching</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./copy-editing.html"> 
<span class="menu-text">Copy Editing</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./going-further.html"> 
<span class="menu-text">Going Further</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./limitations.html"> 
<span class="menu-text">Limitations</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#negotiating-sovereignty-contesting-territory-the-algonquin-lisle-aux-allumettes-and-upper-canada-1835-1839" id="toc-negotiating-sovereignty-contesting-territory-the-algonquin-lisle-aux-allumettes-and-upper-canada-1835-1839" class="nav-link active" data-scroll-target="#negotiating-sovereignty-contesting-territory-the-algonquin-lisle-aux-allumettes-and-upper-canada-1835-1839"><strong>Negotiating Sovereignty, Contesting Territory: The Algonquin, L’Isle-aux-Allumettes, and Upper Canada, 1835-1839</strong></a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content"><header id="title-block-header" class="quarto-title-block"></header>




<section id="negotiating-sovereignty-contesting-territory-the-algonquin-lisle-aux-allumettes-and-upper-canada-1835-1839" class="level1">
<h1><strong>Negotiating Sovereignty, Contesting Territory: The Algonquin, L’Isle-aux-Allumettes, and Upper Canada, 1835-1839</strong></h1>
<p><strong>I. Introduction</strong><br>
<strong>A. Overview of the 1835-1836 Negotiation</strong><br>
In 1835, Algonquin and Nipissing leaders travelled to Toronto, the capital of Upper Canada, to negotiate with Lieutenant-Governor Sir John Colborne. Their objective was to secure recognition of their territorial rights in the Ottawa Valley and establish a reserve, focusing specifically on L’Isle-aux-Allumettes and adjacent lands along the Ottawa River. Having received what they understood to be a favourable response, they returned in 1836 to confirm the arrangement with the new Lieutenant-Governor, Sir Francis Bond Head. However, Head revoked the nascent agreement, citing a pre-existing treaty with the Mississauga Nation as justification for denying the Algonquin claim to the lands south of the island. This sequence of events—an apparent agreement followed by abrupt revocation based on a contested interpretation of another treaty—represents a critical and revealing episode in the complex history of Algonquin-Crown relations and the administration of Indigenous affairs in 19th-century Canada. It highlights the vulnerability of Indigenous land rights in the face of colonial expansion, shifting political administrations, and the powerful influence of resource extraction interests.<br>
<strong>B. Central Research Questions</strong><br>
This report examines the historical context, unfolding events, and immediate aftermath of the 1835-1836 negotiations. It seeks to answer several key questions: What were the historical and legal bases upon which the Algonquin and Nipissing founded their claim to L’Isle-aux-Allumettes and the surrounding Ottawa Valley territory? What specific terms were discussed with Lieutenant-Governor Colborne in 1835, and what commitments, if any, did the Crown make? Why did Lieutenant-Governor Head revoke this understanding in 1836, and how valid was the government’s reliance on a prior Mississauga treaty (the Crawford Purchase) to justify this decision? What do these events reveal about the nature of colonial governance, the interpretation of treaties and Indigenous rights, and the formulation of Indigenous policy in Upper Canada during the turbulent 1830s?<br>
<strong>C. Methodology and Source Distinction</strong><br>
The analysis presented here relies on a careful examination of available primary source materials and secondary scholarly works. Primary sources include petitions submitted by Algonquin and Nipissing leaders, such as the detailed Memorial of June 6, 1835 , and correspondence from colonial officials documenting government responses and internal deliberations, like the 1836 letter detailing Colborne’s position. These are supplemented by records pertaining to the administrations of Lieutenant-Governors Colborne and Head , Executive Council minutes , and documents related to the Mississauga treaties, particularly the Crawford Purchase. Secondary sources encompass scholarly analyses focusing on Algonquin history, the Ottawa Valley timber trade, colonial land policies, and specific government reports like those of Justice Macauley (1839), the Bagot Commission (1842-44), and the Pennefather Commission (1856-58). Throughout this report, a concerted effort is made to clearly distinguish between information drawn directly from primary documents and interpretations offered by historical scholarship, ensuring transparency in the reconstruction of these events. The precarious nature of negotiated understandings that lacked the formal status of ratified treaties becomes evident through this examination; such arrangements proved highly susceptible to changes in colonial personnel and policy priorities.<br>
<strong>D. Scope and Structure</strong><br>
This report focuses specifically on the 1835-1836 negotiations concerning L’Isle-aux-Allumettes and adjacent lands within the jurisdiction of Upper Canada. It situates these events within their deeper historical context, tracing Algonquin presence and rights assertions from the pre-contact era through the early 19th century. The core sections detail the 1835 petition and apparent agreement with Colborne, the 1836 revocation by Head, and the ensuing controversy surrounding the interpretation of the Mississauga treaty. Subsequent government responses and reports up to the late 1830s and early 1840s are examined to understand the immediate policy consequences. The report concludes with a synthesis of findings and an analysis of the significance of this episode.<br>
<strong>II. Historical Context: Algonquin Presence and Claims in the Ottawa Valley</strong><br>
<strong>A. Deep Historical Roots</strong><br>
The Algonquin people possess an ancient connection to the Ottawa River Valley, with archaeological evidence indicating their presence for at least 8,000 years prior to European arrival. Their traditional territory historically encompassed the entire length of the Ottawa River (known in Anishinabemowin as <em>Kitcisìpi</em>, the Great River) and its vast watershed, straddling the present-day border between Ontario and Quebec. Among the distinct Algonquin groups inhabiting this region, the Kichesipirini (“People of the Great River” or, as the French called them, <em>Nation de l’Isle</em> or <em>Savages of the Island</em>) were prominently associated with <em>Kitcesìpìr Mìnìs</em>, now known as Allumette Island (L’Isle-aux-Allumettes). Traditionally, most Algonquin communities practiced a semi-nomadic lifestyle, moving seasonally to hunt, fish, trap, and gather resources, utilizing birchbark canoes for summer travel and snowshoes and toboggans in winter. The Kichesipirini, however, maintained a more permanent settlement on Allumette Island, leveraging its strategic location on the river to control trade and levy tolls on passing canoe flotillas. Archaeological findings on nearby Morrison Island reveal a thousand-year-old culture involved in copper tool manufacturing and extensive trade networks reaching north to Lake Superior and south towards New York.<br>
<strong>B. Post-Contact Era: Alliances, Conflict, and Displacement</strong><br>
The arrival of Europeans profoundly disrupted Algonquin life. Samuel de Champlain encountered the Kichesipirini chief Tessouat in 1603 and later visited their island stronghold in 1613. Alliances were formed, primarily with the French, centered around the lucrative fur trade. However, these alliances, coupled with competition over resources, drew the Algonquin into devastating conflicts with the Haudenosaunee (Iroquois Confederacy), who were allied first with the Dutch and later the English. Compounding the violence were waves of infectious diseases introduced by Europeans, which decimated Indigenous populations. Around 1650, intense warfare led to the near-extermination of the Kichesipirini on Allumette Island by the Iroquois, and the island was largely abandoned by permanent Indigenous settlement for a considerable period, though not necessarily devoid of Algonquin use. Despite these catastrophic events, Algonquin communities persisted in the upper reaches of the Ottawa Valley and its tributaries, adapting to the changed circumstances. Some Algonquin groups relocated, with many converts settling first at Trois-Rivières and then Sillery, weakening the main body defending the Ottawa Valley trade route.<br>
<strong>C. Assertion of Rights under British Rule (Post-1760)</strong><br>
Following the British conquest of New France, the relationship between the Crown and Indigenous peoples was formally outlined in the Royal Proclamation of 1763. This seminal document recognized existing Indigenous rights to land and established that lands could only be alienated through formal treaties made between the Crown and the Indigenous nations occupying them. The Algonquin participated in subsequent treaty councils, such as those at Swegatchy and Kahnawake, and received copies of the Proclamation, understanding it and related agreements (like Governor Carleton’s 1766 proclamation urging settlers to treat Indigenous people as “Friends &amp; Brothers”) as guarantees of their rights and possession of their lands. Wampum belts held by the Algonquin commemorate these agreements and commitments.<br>
As Loyalist settlement pressures increased after the American Revolution (1783), the Algonquin became increasingly concerned about encroachment on their traditional territories. They began petitioning the government, asserting their rights and requesting protection. A notable instance occurred in July 1794, when Algonquin and Nipissing chiefs met with Colonel John Campbell, Deputy Superintendent of the Indian Department, in Quebec. They explicitly complained about Iroquois incursions and settler pressure forcing other tribes onto their hunting grounds, stating unequivocally that they “had not sold our lands above Long Sault” on the Ottawa River. They detailed mistreatment by specific settlers like “Captain Fortune,” who restricted their access to fishing, hunting, and even firewood. While willing to accommodate limited settlement along the river (requesting grants be no more than forty arpents deep), they urgently pleaded that lands extending into their tributary rivers not be granted, as this would destroy their subsistence. They appealed to their status as the original, peaceful possessors,f these lands?“.<br>
This consistent assertion of rights faced an administrative complication with the Constitutional Act of 1791, which established Upper and Lower Canada, using the Ottawa River as the boundary. This act arbitrarily divided the Algonquin homeland between two separate colonial jurisdictions, hindering unified administration and recognition of their claims.<br>
The historical record demonstrates a continuous Algonquin assertion of rights based on ancestral occupation and Crown commitments like the Royal Proclamation, despite significant historical disruptions and administrative fragmentation. However, colonial authorities often viewed these claims through a different lens, sometimes emphasizing historical events like the 17th-century Iroquois conflicts or the 1791 administrative boundary to minimize or dismiss Algonquin title, particularly when it conflicted with settlement or resource interests. This reveals a persistent divergence between Indigenous understandings of ongoing stewardship and relationship to the land, and a colonial framework focused on discrete land cessions and jurisdictional lines.<br>
Furthermore, the economic basis of the colonial relationship shifted significantly in the early 19th century. While the earlier fur trade economy valued Algonquin knowledge and control of river networks , the rise of the timber industry transformed the Ottawa Valley’s forests into commodities and fueled demand for land settlement. This transition, accelerating in the 1830s, placed intense pressure on Algonquin hunting grounds and resources, leading directly to the conflicts and dispossession that characterized the period. The Algonquins’ own petitions lamented the destruction caused by settlers and loggers, and later government reports implicitly acknowledged the timber industry’s role in necessitating Algonquin displacement.<br>
<strong>III. The 1835 Petition and Negotiation with Lt. Governor Colborne</strong><br>
<strong>A. The Petition of June 6, 1835</strong><br>
Against this backdrop of increasing pressure and diminishing resources, Algonquin and Nipissing leaders sought direct intervention from the Crown’s representative. On June 6, 1835, they presented a”humble Memorial” to Major General Sir John Colborne, then Lieutenant-Governor of Upper Canada, during a visit to Toronto. Colborne held this post from 1828 until early 1836.<br>
The text of the 1835 petition provides a clear articulation of their grievances and claims. The Chiefs and Warriors, speaking for their nations, asserted their “immemorial” occupation and enjoyment of hunting grounds on both sides of the Ottawa River up to Lake Nipissing. They pointedly stated that extensive land grants had been made and settlements established by Colborne’s predecessors on these territories—specifically mentioning the south side of the Ottawa within Upper Canada—without any purchase having been made or compensation offered, actions they viewed as contrary to the King’s promises, implicitly referencing the Royal Proclamation. They emphasized their unique vulnerability, noting that unlike other tribes, they possessed no lands yielding revenue and were “solely dependent upon the Chase on our Hunting Grounds for support and Maintenance.” This reliance was critically threatened, they argued, by the “rapidly increasing Settlement” and the “indiscriminate and wanton Destruction by the Whites or new Settlers of the Beaver and other Animals,” which would soon “annihilate our Chase.” Consequently, they felt “irresistibly compelled” to seek “reasonable Indemnification” for the lands already lost on the south side of the river and requested that the Crown “ratify and confirm” their “Use, Occupation, and Possession” of the hunting grounds still remaining to them on that side. Finally, they asked Colborne to command, by proclamation or otherwise, that all “Intruders or Squatters” be removed from these remaining lands.<br>
<strong>B. Proposed Transition to Agriculture</strong><br>
While the 1835 petition text focuses on hunting rights and compensation for lost grounds, the context surrounding the negotiations indicates an awareness among the Algonquin leadership of the need to adapt their economy. The petition’s own description of the destruction of the hunt underscores the unsustainability of relying solely on traditional practices in the face of rapid settlement and resource depletion. Scholarly analysis suggests that the Algonquin proposed L’Isle-aux-Allumettes partly because its location offered potential for establishing a more settled agricultural base, alongside continued access to remaining hunting territories further upriver. This aligns with broader colonial policies of the era, which increasingly promoted agriculture and settlement as the desired future for Indigenous peoples, often as a precursor to assimilation.<br>
<strong>C. The Focus on L’Isle-aux-Allumettes</strong><br>
L’Isle-aux-Allumettes emerged as the specific focal point for the proposed reserve. Situated further up the Ottawa River, it was relatively remote from the main thrust of settlement advancing westward from the St.&nbsp;Lawrence at that time. For the Algonquin, it represented a part of their ancestral territory where they might consolidate their community and adapt their way of life. According to Lawson’s analysis, the Algonquin even contemplated allowing existing non-Aboriginal squatters on the island to remain, provided they paid rent to the Algonquin Nation, suggesting a pragmatic approach aimed at securing both land tenure and a potential source of revenue.<br>
<strong>D. Colborne’s Response (Apparent Agreement)</strong><br>
The Algonquin delegation seemingly left Toronto in 1835 with the impression that they had secured Colborne’s agreement, or at least his strong support. This perception is supported by subsequent communications from Colborne’s administration. A letter dated February 26, 1836, from Colonel James Givins, Chief Superintendent of the Indian Department in Toronto, to Lieutenant-Colonel D.C. Napier, Secretary for Indian Affairs in Quebec, conveyed Colborne’s position regarding the Algonquin and Nipissing petition. With respect to their request for securing possession of their remaining hunting grounds on the south side of the Ottawa, the letter stated: “His Excellency desires me to express his readiness to assist as far as possible, The Petitioners in settling on such part of those grounds as they may select, and as far as it may be practicable to protect them against The Intrusion of strangers”.<br>
While seemingly positive, the documented commitment from Colborne’s administration contained significant ambiguities. The language used – “assist as far as possible,” allowing settlement on lands “as they may select,” and protection “as far as it may be practicable” – stopped short of explicitly confirming Algonquin title to L’Isle-aux-Allumettes or guaranteeing the specific reserve boundaries and indemnification they sought. The focus on facilitating <em>settlement</em> aligned with prevailing colonial objectives but did not fully address the Algonquin’s fundamental claims based on the Royal Proclamation and immemorial rights. This lack of precise, legally binding language left the arrangement vulnerable to reinterpretation or outright dismissal by Colborne’s successor.<br>
<strong>IV. The 1836 Revocation under Lt. Governor Head</strong><br>
<strong>A. Change in Leadership</strong><br>
The political landscape in Upper Canada shifted significantly in early 1836. Sir John Colborne departed, and Sir Francis Bond Head arrived in Toronto in January to assume the role of Lieutenant-Governor. Head, a former military officer and Poor Law commissioner with little colonial experience, arrived during a period of intense political conflict between Reformers and the ruling elite (often dubbed the “Family Compact”). Although initially welcomed by Reformers, Head quickly alienated them through his partisan actions, refusal to consult his Executive Council, and eventual dissolution of the Reform-dominated Assembly, leading to a bitter election campaign in 1836 which he won by appealing to Loyalist sentiments. His administration was marked by confrontation and ultimately contributed to the outbreak of the Rebellion of 1837. This political context suggests an administrator preoccupied with internal colonial power struggles and potentially less inclined to engage sympathetically with complex Indigenous land claims that might impede settlement or resource development favored by his political allies.<br>
<strong>Table 1: Key Individuals and Roles (c.&nbsp;1835-1839)</strong></p>
<table class="caption-top table">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Name</th>
<th style="text-align: left;">Role/Title</th>
<th style="text-align: left;">Key Actions/Stance related to Algonquin Claim</th>
<th style="text-align: left;">Relevant Sources</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Sir John Colborne</td>
<td style="text-align: left;">Lieutenant-Governor of Upper Canada (1828-1836)</td>
<td style="text-align: left;">Received 1835 Algonquin/Nipissing petition; Expressed readiness (via Givins) to assist with settlement and offer protection “as far as practicable”.</td>
<td style="text-align: left;"></td>
</tr>
<tr class="even">
<td style="text-align: left;">Sir Francis Bond Head</td>
<td style="text-align: left;">Lieutenant-Governor of Upper Canada (1836-1838)</td>
<td style="text-align: left;">Met 1836 Algonquin delegation; Revoked prior understanding; Cited Mississauga treaty as reason for denial; Offered only resettlement assistance.</td>
<td style="text-align: left;"></td>
</tr>
<tr class="odd">
<td style="text-align: left;">Col. James Givins</td>
<td style="text-align: left;">Chief Superintendent, Indian Dept. (Toronto)</td>
<td style="text-align: left;">Communicated Colborne’s response regarding the 1835 petition to Napier in Feb 1836.</td>
<td style="text-align: left;"></td>
</tr>
<tr class="even">
<td style="text-align: left;">Lt. Col. D.C. Napier</td>
<td style="text-align: left;">Secretary, Indian Affairs (Quebec)</td>
<td style="text-align: left;">Received communication from Givins regarding Colborne’s stance.</td>
<td style="text-align: left;"></td>
</tr>
<tr class="odd">
<td style="text-align: left;">Justice J.B. Macauley</td>
<td style="text-align: left;">Judge / Commissioner</td>
<td style="text-align: left;">Authored 1839 report addressing Algonquin claim/Mississauga treaty boundary; Proposed compromise boundary line; Recommended Algonquin relocation.</td>
<td style="text-align: left;"></td>
</tr>
<tr class="even">
<td style="text-align: left;">Algonquin/Nipissing Chiefs</td>
<td style="text-align: left;">Leaders representing their Nations</td>
<td style="text-align: left;">Petitioned Colborne in 1835 asserting rights, seeking compensation and reserve; Met with Head in 1836 to confirm agreement.</td>
<td style="text-align: left;"></td>
</tr>
</tbody>
</table>
<p><strong>B. The Algonquin Delegation to Toronto (1836)</strong><br>
Trusting in the commitments made the previous year, an Algonquin delegation returned to Toronto in 1836. They had consulted with their nation and were prepared to discuss the transition to agriculture, believing they were moving forward with the plan to establish a reserve at L’Isle-aux-Allumettes. They arrived to find Head newly installed as Lieutenant-Governor.<br>
<strong>C. Head’s Revocation and Rationale</strong><br>
The meeting with Lieutenant-Governor Head proved disastrous for the Algonquin hopes. Head refused to honour the understanding reached with Colborne. His justification, as reported by the Algonquin and analyzed by scholars, was that the lands in question—specifically the south bank of the Ottawa River adjacent to L’Isle-aux-Allumettes—had already been surrendered to the Crown by the Mississauga Nation through previous treaties. Consequently, the Crown could not grant these lands to the Algonquin. Head effectively dismissed the Algonquin petition’s core claims regarding their own ancestral rights and the lack of prior cession by them. Instead of confirming a reserve or discussing compensation, he offered only potential assistance with resettlement elsewhere, mirroring the general policy direction favouring the concentration of Indigenous peoples away from settlement frontiers. This stance represented a complete reversal of the position communicated by Colborne’s administration just months earlier.<br>
The timing and rationale behind Head’s decision suggest that the invocation of the Mississauga treaty may have served as a convenient justification to nullify Colborne’s potentially burdensome commitment. Head was embroiled in domestic political conflicts and aligned himself with forces favouring settlement and resource exploitation. Acknowledging Algonquin title and establishing a reserve, particularly one that might include rent-paying squatters as envisioned by the Algonquin , could hinder these objectives. Furthermore, the timber trade, a major economic engine in the Ottawa Valley, relied on access to the river and surrounding forests. Using an interpretation of a pre-existing treaty with a different Indigenous nation allowed Head to sidestep the specific claims and historical context presented by the Algonquin in their 1835 petition , thereby avoiding the creation of perceived impediments to colonial expansion under the guise of upholding a prior agreement.<br>
<strong>V. The Mississauga Treaty Controversy</strong><br>
<strong>A. The Government’s Position (Post-1836)</strong><br>
Following Head’s 1836 decision, the official government position solidified: the lands along the south bank of the Ottawa River opposite L’Isle-aux-Allumettes, and arguably the island itself (given its proximity and the claim’s focus on adjacent lands), were deemed to have been previously ceded by the Mississauga. By 1837, officials explicitly stated that the island was considered part of southeastern lands already surrendered by the Mississauga Anishinabeg.<br>
<strong>B. Identifying the Relevant Treaty - The Crawford Purchase (1783)</strong><br>
The specific agreement underpinning the government’s claim was the Crawford Purchase, negotiated in October 1783. This was one of several early land agreements made by the British Crown in the immediate aftermath of the American Revolution. Its primary purpose was to secure lands along the St.&nbsp;Lawrence River and the northeastern shore of Lake Ontario to resettle Loyalists, including Haudenosaunee allies, who had supported Britain during the war and were displaced from the newly formed United States. Captain William Crawford negotiated the purchase with Mississauga representatives.<br>
<strong>C. The Crux of the Dispute: Boundary Ambiguity</strong><br>
The central issue enabling the government’s 1836 stance was the profound ambiguity surrounding the northern boundary of the Crawford Purchase. Captain Crawford’s own report on the agreement described the acquired territory as extending from the Toniato River (near Gananoque) westward to a river in the Bay of Quinte, “extending from the lake back as far as a man can travel in a day,” and including all islands. This description is inherently vague. The phrase “as far as a man can travel in a day” is imprecise and open to wide interpretation. Crucially, the Ottawa River is not explicitly mentioned as the northern boundary in the primary accounts of the purchase.<br>
This ambiguity persisted long after 1783. Later government documents and maps displayed conflicting interpretations of the purchase’s extent. Significantly, an 1847 map titled “Plan shewing the different surrenders made by the Indians in Upper Canada to the Crown” depicted the area presumed to be the Crawford Purchase as <em>unceded</em> land. Furthermore, historical accounts note that another Indigenous leader, Chief Mynass from Kanesatake (Oka), also claimed territory overlapping the Crawford Purchase area and extending north to the Ottawa River, adding another layer of complexity and contested ownership recognized by some contemporaneous officials. The irregularity of these early purchases, conducted under pressure to secure land quickly for refugees and potentially facilitated by inducements like rum, was significant.<br>
<strong>D. The Algonquin Counter-Argument</strong><br>
The Algonquin vehemently contested the interpretation that the Crawford Purchase extinguished their rights along the Ottawa River. Their understanding, rooted in traditional territorial frameworks, was that Mississauga territory did not extend north to the Ottawa River. They argued that the boundary lay along the height of land, the watershed divide separating the St.&nbsp;Lawrence River system from the Ottawa River system. This perspective aligns with common Indigenous practices of defining territories based on natural geographic features like river basins and watersheds.<br>
<strong>E. Justice Macauley’s 1839 Report</strong><br>
The boundary dispute became a subject of official review. In 1839, Justice J.B. Macauley was tasked with reporting on various Indian affairs matters, including the Algonquin claims. His report acknowledged the uncertainty surrounding the northern limit of the Crawford Purchase. As a potential resolution to the boundary question itself, Macauley proposed drawing a simplified line midway between the St.&nbsp;Lawrence and Ottawa Rivers. The very fact that such a compromise line was suggested implicitly confirms that the original 1783 agreement lacked the clarity needed to definitively place the boundary at the Ottawa River.<br>
However, Macauley’s primary recommendation transcended the boundary issue. He concluded that the most expedient solution was the removal and relocation of the Algonquin people from the disputed region altogether. This indicates that, for the colonial administration, resolving the technicalities of the boundary was less important than clearing the land for settlement and resource exploitation.<br>
The government’s deployment of the ambiguous Crawford Purchase against the Algonquin claim appears as a strategic maneuver. By leveraging the uncertainty inherent in the 1783 agreement with the Mississauga, colonial officials could create a legal pretext to ignore the specific claims and prior commitments made directly to the Algonquin and Nipissing. The boundary dispute, rather than being a genuine search for historical accuracy, served as a tool of legal obfuscation to facilitate colonial expansion and negate Algonquin rights in the Ottawa Valley.<br>
<strong>VI. Post-Revocation: Government Reports and Continued Algonquin Marginalization</strong><br>
<strong>A. Macauley Report (1839) Implications</strong><br>
Justice Macauley’s 1839 report, while addressing the boundary dispute, ultimately pointed towards a policy of removal rather than accommodation. His recommendation to relocate the Algonquin signaled a clear governmental preference for extinguishing Indigenous presence in areas desired for settlement and industry. Tellingly, Macauley suggested that the costs associated with this relocation, potentially including annuities for the lost lands, should be funded through charges levied on timber licenses. This proposal explicitly connected Algonquin displacement to the economic imperatives of the burgeoning timber trade, acknowledging, albeit indirectly, that the industry driving the conflict should bear some responsibility for its consequences.<br>
<strong>B. Bagot Commission (1842-1844)</strong><br>
Further shaping Indian policy in the Province of Canada (formed by the union of Upper and Lower Canada in 1841) was the Commission appointed in 1842 under Governor Sir Charles Bagot. Tasked with a comprehensive inquiry into the management of Indian Affairs, the commission, led by Rawson W. Rawson, John Davidson, and William Hepburn, examined the condition of various Indigenous groups, including Algonquins residing in Canada East (formerly Lower Canada) and other “unsettled Tribes”.<br>
The Bagot Commission’s report, submitted in 1844, drew a distinction between the perceived land status in the two formerly separate provinces. It noted that in Canada West (formerly Upper Canada), Indigenous peoples were generally considered the original occupants, necessitating formal land cession treaties as settlement progressed. In contrast, the commissioners suggested that in Canada East, prior French land grants to Indigenous communities (like those at Sillery or Oka/Kanesatake) had effectively confined their territorial rights to specific, defined tracts. This perspective could have influenced how officials viewed claims, like those of the Algonquin, that spanned the Ottawa River boundary. The Bagot report also endorsed Justice Macauley’s earlier findings, including his rejection of Indigenous claims to a “separate nationality” distinct from Crown subjects. While specific details regarding the 1835-36 L’Isle-aux-Allumettes negotiations may not be prominent in the main report , its overall framework reinforced a move towards greater government control and assimilationist policies.<br>
<strong>C. Pennefather Commission (1856-1858)</strong><br>
Building upon the Bagot Commission’s work, the Special Commissioners to Investigate Indian Affairs in Canada (often called the Pennefather Commission after Richard T. Pennefather) conducted further inquiries between 1856 and 1858. Their report reflected an intensification of assimilationist goals. They recommended consolidating scattered Indigenous bands onto larger, centralized reserves (such as Manitoulin Island, Garden River, Walpole Island) to facilitate administration and agricultural instruction. Critically, the Pennefather Commission went further than Bagot, suggesting that if Indigenous groups refused to surrender their smaller reserves and relocate, the government should consider expropriating their lands, arguing that reserve enclaves could not be allowed to impede provincial development. This recommendation underscored the hardening colonial stance, prioritizing settlement and economic progress over established Indigenous land tenure.<br>
<strong>D. Continued Algonquin Petitions and Marginalization</strong><br>
Despite the government’s shift towards policies of removal and assimilation, the Algonquin people continued to assert their rights and protest their treatment. An 1847 petition, for instance, vividly described the negative impacts of settlement and logging. The petitioners lamented the loss of their former independence and wealth (“In those days Father we were happy, rich and independent”), contrasting it with their current poverty caused by the destruction of forests and game. They complained of being “ill treated by these interlopers” who destroyed their small maize patches and sugar bushes, and noted their powerlessness: “We are too weak Father to defend ourselves and obliged to put up with these injuries and injustices”. They reiterated their claim as the rightful proprietors based on the Royal Proclamation and ancestral occupation.<br>
Throughout the remainder of the 19th century, Algonquin communities in the Ottawa Valley faced ongoing dispossession and marginalization. Many who did not relocate to designated reserves like Golden Lake (Pikwakanagan) remained as “non-status” Indians, living dispersed throughout their traditional territory but lacking official recognition or protection from the Indian Department. Their attempts to maintain traditional subsistence practices were increasingly hampered by resource depletion and restrictive laws. The history of these communities, often overlooked in official records, has been painstakingly reconstructed through research utilizing archival documents and oral histories by firms such as Joan Holmes &amp; Associates, often in the context of modern land claim negotiations.<br>
The trajectory of government policy following the 1836 revocation reveals a decisive shift. Where Colborne’s administration offered at least ambiguous recognition and potential protection on existing lands , Head’s denial , Macauley’s relocation proposal , and the subsequent recommendations of the Bagot and Pennefather Commissions demonstrate a clear move towards strategies aimed at extinguishing Algonquin title, consolidating populations onto reserves, promoting agriculture, and ultimately assimilating Indigenous peoples into the dominant colonial society. This policy evolution sought to erase distinct Algonquin presence and claims across large swathes of the Ottawa Valley, paving the way for unimpeded settlement and resource extraction, despite persistent Algonquin resistance.<br>
<strong>Table 2: Timeline of Key Events (1763 - c.&nbsp;1847)</strong></p>
<table class="caption-top table">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Date(s)</th>
<th style="text-align: left;">Event</th>
<th style="text-align: left;">Significance</th>
<th style="text-align: left;">Relevant Sources</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">1763</td>
<td style="text-align: left;">Royal Proclamation</td>
<td style="text-align: left;">Establishes principles for Indigenous land rights and treaty-making.</td>
<td style="text-align: left;"></td>
</tr>
<tr class="even">
<td style="text-align: left;">Oct 1783</td>
<td style="text-align: left;">Crawford Purchase</td>
<td style="text-align: left;">Mississauga cede land along St.&nbsp;Lawrence/Lake Ontario; boundaries ambiguous, later used to contest Algonquin claims.</td>
<td style="text-align: left;"></td>
</tr>
<tr class="odd">
<td style="text-align: left;">1791</td>
<td style="text-align: left;">Constitutional Act</td>
<td style="text-align: left;">Divides Province of Quebec into Upper &amp; Lower Canada, splitting Algonquin territory along Ottawa River.</td>
<td style="text-align: left;"></td>
</tr>
<tr class="even">
<td style="text-align: left;">July 1794</td>
<td style="text-align: left;">Algonquin/Nipissing Council with Col. Campbell</td>
<td style="text-align: left;">Early formal assertion of rights, complaint re: encroachment, statement of non-cession “above Long Sault”.</td>
<td style="text-align: left;"></td>
</tr>
<tr class="odd">
<td style="text-align: left;">June 6, 1835</td>
<td style="text-align: left;">Algonquin/Nipissing Petition to Lt. Gov.&nbsp;Colborne</td>
<td style="text-align: left;">Formal request for confirmation of rights, compensation for lost lands, reserve (focusing on L’Isle-aux-Allumettes), and protection.</td>
<td style="text-align: left;"></td>
</tr>
<tr class="even">
<td style="text-align: left;">Jan 1836</td>
<td style="text-align: left;">Sir Francis Bond Head becomes Lt. Gov.&nbsp;of Upper Canada</td>
<td style="text-align: left;">Change in colonial leadership brings new political dynamics and priorities.</td>
<td style="text-align: left;"></td>
</tr>
<tr class="odd">
<td style="text-align: left;">Feb 26, 1836</td>
<td style="text-align: left;">Col. Givins letter re: Colborne’s stance</td>
<td style="text-align: left;">Documents Colborne administration’s (ambiguous) commitment to assist with settlement and protection.</td>
<td style="text-align: left;"></td>
</tr>
<tr class="even">
<td style="text-align: left;">Spring/Summer 1836</td>
<td style="text-align: left;">Algonquin delegation meets Head in Toronto</td>
<td style="text-align: left;">Algonquin seek confirmation of 1835 understanding; Head revokes it, citing Mississauga treaty.</td>
<td style="text-align: left;"></td>
</tr>
<tr class="odd">
<td style="text-align: left;">1837</td>
<td style="text-align: left;">Govt. officials assert Mississauga cession includes island</td>
<td style="text-align: left;">Formal articulation of the legal justification for Head’s revocation.</td>
<td style="text-align: left;"></td>
</tr>
<tr class="even">
<td style="text-align: left;">1839</td>
<td style="text-align: left;">Justice Macauley Report</td>
<td style="text-align: left;">Addresses boundary dispute (proposes compromise line); Primarily recommends Algonquin relocation, funded by timber licenses.</td>
<td style="text-align: left;"></td>
</tr>
<tr class="odd">
<td style="text-align: left;">1842-1844</td>
<td style="text-align: left;">Bagot Commission Inquiry &amp; Report</td>
<td style="text-align: left;">Major review of Indian Affairs; distinguishes UC/LC land status; endorses Macauley; reinforces assimilationist trend.</td>
<td style="text-align: left;"></td>
</tr>
<tr class="even">
<td style="text-align: left;">Aug 1847</td>
<td style="text-align: left;">Further Algonquin Petition</td>
<td style="text-align: left;">Demonstrates continued assertion of rights, documentation of grievances (encroachment, resource destruction), appeals to Crown promises.</td>
<td style="text-align: left;"></td>
</tr>
</tbody>
</table>
<p><strong>VII. Conclusion</strong><br>
<strong>A. Summary of Findings</strong><br>
The attempt by the Algonquin and Nipissing Nations in 1835-1836 to secure a reserve at L’Isle-aux-Allumettes and confirm their rights in the Ottawa Valley represents a poignant case study in the complexities and inequities of Indigenous-Crown relations in 19th-century Upper Canada. Grounded in immemorial occupation and the principles of the Royal Proclamation, the Algonquin presented a formal petition to Lieutenant-Governor Colborne in 1835, outlining their grievances concerning land loss and resource depletion, and seeking confirmation of their remaining territory, compensation, and protection. While Colborne’s administration offered an encouraging, albeit ambiguously worded, response indicating willingness to assist with settlement and protection , this understanding was swiftly overturned by his successor, Sir Francis Bond Head, in 1836. Head invoked the prior, and vaguely defined, Crawford Purchase of 1783 with the Mississauga Nation as justification for denying the Algonquin claim to lands adjacent to the island. Subsequent government reports, notably by Justice Macauley in 1839 and the Bagot Commission in the early 1840s, reinforced this denial and shifted policy towards the relocation and assimilation of the Algonquin people, rather than accommodation of their rights within their traditional territory.<br>
<strong>B. Analysis of Failure</strong><br>
The failure of the 1835-1836 negotiation stemmed from a confluence of factors deeply embedded in the colonial context. Firstly, the absence of a formally ratified treaty resulting from the 1835 discussions left the arrangement precarious and dependent on the goodwill of individual administrators. The documented response from Colborne’s office lacked the specific, binding language necessary to guarantee title or reserve boundaries. Secondly, the change in leadership from Colborne to the politically embattled and partisan Sir Francis Bond Head proved critical. Head’s administration prioritized colonial expansion and loyalty politics over nuanced engagement with Indigenous claims. Thirdly, the inherent ambiguity surrounding the northern boundary of the 1783 Crawford Purchase provided a convenient, if questionable, legal pretext for Head’s administration to dismiss the Algonquin petition. Finally, and perhaps most fundamentally, the overriding pressures of settler expansion and the demands of the burgeoning timber industry created a political and economic environment where respecting Algonquin territorial integrity was seen as an impediment to progress.<br>
<strong>C. Significance and Legacy</strong><br>
The events surrounding L’Isle-aux-Allumettes in 1835-1836 had lasting consequences for the Algonquin people. The denial of their claim and the subsequent policies of relocation and assimilation contributed significantly to their ongoing dispossession and marginalization within their Ottawa Valley homeland. The failure to secure a recognized land base exacerbated their vulnerability to encroachment and resource depletion, as lamented in their later petitions. This episode exemplifies broader patterns observed across Canada during this era: the erosion of Indigenous land rights through contested treaty interpretations, the prioritization of settlement and resource extraction over Crown obligations, the impact of shifting administrative personnel and policies, and the persistent efforts of Indigenous nations to assert their rights despite facing overwhelming colonial power. The legacy of this period continues to resonate in contemporary Algonquin land claims, such as the comprehensive claim by the Algonquins of Ontario, which seeks to finally address the unresolved issues stemming from the lack of treaties covering vast portions of their ancestral territory.<br>
<strong>D. Final Considerations on Source Interpretation</strong><br>
This historical episode underscores the critical importance of engaging rigorously with diverse sources. The Algonquin petition of 1835 offers a direct voice articulating their perspective and claims. Government correspondence reveals internal deliberations and official justifications, but must be read critically, recognizing potential biases and administrative objectives. Scholarly analyses provide essential context and interpretation but should be assessed alongside the primary evidence. Government reports, such as Macauley’s or the Bagot Commission’s, reflect the policy thinking of the time but were often framed by assimilationist assumptions and colonial priorities. Understanding the nuances, ambiguities, and contradictions within and between these sources is crucial for reconstructing a more complete and just understanding of the past and its enduring impact on the present.<br>
<strong>VIII. Bibliography</strong><br>
<em>(Note: This bibliography lists sources based on the provided snippet identifiers. Full bibliographic details would require accessing the original documents.)</em></p>
<ul>
<li>Algonquin Petition of June 6, 1835.<br>
</li>
<li>Algonquin Petition of August 1847.<br>
</li>
<li>Bagot Commission Report (Commissioners Appointed to inquire into the Affairs of the Indians in Canada), 1844/45.<br>
</li>
<li>Buckner, Phillip A. “Head, Sir Francis Bond.” <em>The Canadian Encyclopedia</em>, 2008 (edited 2015).<br>
</li>
<li>Buckner, Phillip A. “Head, Sir Francis Bond.” <em>Dictionary of Canadian Biography</em>, vol.&nbsp;10, 1972.<br>
</li>
<li>Canniff, Wm. <em>History of the Settlement of Upper Canada, (Ontario,) With Special Reference to the Bay Quinté</em>. Dudley &amp; Burns, 1869.<br>
</li>
<li><em>Chronology of the Algonquins of Golden Lake Claim</em>, Vol. 5. Prepared by Joan Holmes &amp; Associates, Inc.&nbsp;for Ontario Native Affairs Secretariat, 1993.<br>
</li>
<li>Clouthier, L. “Submission to the Algonquins of Ontario Tribunal…” February 2023.<br>
</li>
<li>Coffin, Nathaniel. Glenbow-Alberta Institute, Glenbow Museum, 1835.<br>
</li>
<li>Cook, Nelson. <em>Sir Francis Bond Head, Lieutenant-Governor of Upper Canada, 1793-1875</em>. Mezzotint, 1837. Library and Archives Canada.<br>
</li>
<li><em>Crawford Purchase National Historic Event</em>. Parks Canada.<br>
</li>
<li>Cruikshank, Ernest Alexander. “An Address on unveiling a tablet…” <em>Ontario Historical Society Papers and Records</em>, Vol. 25 (1929).<br>
</li>
<li><em>Descriptive essays contributed to the Quarterly review</em> by Sir Francis Bond Head. J. Murray, 1857.<br>
</li>
<li><em>The Emigrant</em> by Sir Francis Bond Head. J. Murray, 1846/1852; Harper and brothers, 1847.<br>
</li>
<li>Enrolment Officer’s Report Regarding Ancestor Thomas Lagarde dit St Jean. Algonquins of Ontario, 2022.<br>
</li>
<li>Ferguson, Veldon. <em>Algonquin History in The Ottawa River Watershed</em>. 2006?<br>
</li>
<li>Foran, Timothy. <em>Defining Métis: Catholic Missionaries and the Idea of Civilization in Northwestern Saskatchewan, 1845–1898</em>. PhD dissertation, University of Ottawa, 2011.<br>
</li>
<li>Fraser, Robert L. “Hillier, George.” <em>Dictionary of Canadian Biography</em>, vol.&nbsp;7, 1988.<br>
</li>
<li><em>Guide to the Holdings of the Archives of Ontario Volume Two</em>. Archives of Ontario, 199?.<br>
</li>
<li>Head, Sir Francis Bond. <em>A Narrative</em>. London: John Murray, 1839.<br>
</li>
<li>Head, Sir Francis Bond. <em>Communications and Despatches Relating to Recent Negociations With the Indians</em>. Toronto?, 1836?.<br>
</li>
<li><em>Historical Development of the Indian Act</em>. Treaties and Historical Research Centre, P.R.E. Group, Indian and Northern Affairs Canada, 1978 (2nd ed.).<br>
</li>
<li><em>History of the Administration of the Indian Affairs Branch</em>. Indian and Northern Affairs Canada, 1983.<br>
</li>
<li><em>A History of the Algonquins</em>. Tanakiwin, n.d.<br>
</li>
<li>Holmes, Joan &amp; Associates Inc.&nbsp;<em>Report on the Algonquins of Golden Lake Claim</em>. Prepared for Ontario Native Affairs Secretariat, 1993.<br>
</li>
<li>Huitema, Marijke E. <em>“Land of Which the Savages Stood in No Particular Need”: Dispossessing the Algonquins of South-Eastern Ontario of their Lands, 1760-1930</em>. M.A.&nbsp;Thesis, Queen’s University, 2000.<br>
</li>
<li><em>Indian Treaties and Surrenders from 1680 to 1890</em>. Vol. I-II. Ottawa: Queen’s Printer, 1891. (Likely source for treaty texts/details cited in gov docs).<br>
</li>
<li><em>Information on JHA Enrolment Team</em>. Algonquins of Ontario, 2023.<br>
</li>
<li><em>Initial Synthesis Report on Métis Archival Research</em>. Métis National Council, 2011.<br>
</li>
<li><em>Joan Holmes &amp; Associates Inc.</em> Website.<br>
</li>
<li><em>Journal of the House of Assembly of Upper Canada</em>. Toronto: M. Reynolds, 1836.<br>
</li>
<li>Lawson, Russell. “Aboriginal Dispossession in the Emergence of a Capitalist Resource Extractive Region: The Ottawa Valley, 1800-1830s.” Paper presented to the Canadian Political Science Association, 2009.<br>
</li>
<li>Leslie, John F. <em>Commissions of Inquiry into Indian Affairs in the Canadas, 1828-1858: Evolving a Policy</em>. MA Thesis, Carleton University, 1984 / INAC Publication, 1985.<br>
</li>
<li><em>List of colonial governors in 1836</em>. Wikipedia.<br>
</li>
<li><em>List of governors general of Canada</em>. Wikipedia.<br>
</li>
<li><em>L’Isle-aux-Allumettes</em>. Wikipedia.<br>
</li>
<li><em>Map of Ontario Treaties and Reserves</em>. Government of Ontario.<br>
</li>
<li><em>MRC Pontiac: History of the Pontiac</em>. MRC Pontiac.<br>
</li>
<li>Mulvany, C. Pelham. <em>History of Toronto and County of York, Ontario</em>. Vol. 1. C. Blackett Robinson, 1885.<br>
</li>
<li>Murray, Laura J. “Settler and Indigenous Stories of Kingston/Ka’tarokwi.” <em>Journal of Canadian Studies</em> 52:1 (2018): 249-279.<br>
</li>
<li><em>Negotiation Processes</em>. Algonquins of Ontario.<br>
</li>
<li><em>Our Proud History</em>. Algonquins of Ontario.<br>
</li>
<li><em>Ottawa River Heritage Designation</em>. Ottawa River Project.<br>
</li>
<li>Pabla, Jasnit. “Realizing the duty to acknowledge: a brief history of recognizing land at Queen’s.” <em>Queen’s Journal</em>, March 22, 2019.<br>
</li>
<li>Parkman, Francis. <em>The Jesuits in North America in the Seventeenth Century</em>. 1867.<br>
</li>
<li><em>Past Recovery Archaeological Services Inc.</em> Reports.<br>
</li>
<li>Pennefather Commission Report (Report of the Special Commissioners Appointed on the 8th of September, 1856, to Investigate Indian Affairs in Canada), 1858.<br>
</li>
<li><em>Pontiac Ouest: History of the Pontiac</em>. Pontiac Ouest.<br>
</li>
<li><em>Pre-Confederation Governors</em>. Lieutenant Governor of Ontario Office.<br>
</li>
<li>Public Archives of Canada / Library and Archives Canada Records (RG1, RG10, CO42Q, MG11, etc.).<br>
</li>
<li>Read, D.B. <em>The Lieutenant-Governors of Upper Canada and Ontario 1792-1899</em>. William Briggs, 1900.<br>
</li>
<li><em>Rebellion in Upper Canada</em>. <em>The Canadian Encyclopedia</em>.<br>
</li>
<li><em>Report on Native Claims</em>. Research Branch, Corporate Policy, Indian and Northern Affairs Canada, 1983/1986.<br>
</li>
<li><em>Report on the Survey of Indian Lands on the North Shore of Lake Huron</em>. Department of Crown Lands, 1951.<br>
</li>
<li>Schmalz, Peter S. <em>The Ojibwa of Southern Ontario</em>. University of Toronto Press, 1991.<br>
</li>
<li>Shanahan, David. “The Crawford ‘Purchases’.” <em>Anishinabek News</em>, November 3, 2021.<br>
</li>
<li>Shanahan, David. “Land for goods: the Crawford Purchases.” <em>Anishinabek News</em>, November 8, 2018.<br>
</li>
<li>Simcoe, John Gra*. University of Toronto Press, 1987 (repr. 2013).<br>
</li>
<li>Stelter, Emma. <em>Polishing and Tarnishing the Chain: An Examination of Mississauga Treaties around the Head of Lake Ontario, 1780-1820</em>. MA Thesis, University of Guelph, 2021.<br>
</li>
<li>Surtees, Robert J. <em>Indian Land Surrenders in Ontario 1763-1867</em>. Indian and Northern Affairs Canada, 1983.<br>
</li>
<li><em>Technical Advisory Group</em>. Algonquins of Ontario.<br>
</li>
<li><em>Treaty Land Surrenders in Ontario</em>. Crown-Indigenous Relations and Northern Affairs Canada.<br>
</li>
<li><em>Treaty Timeline</em>. Great Lakes Research Alliance for the Study of Aboriginal Arts and Cultures (GRASAC).<br>
</li>
<li><em>12th Parliament of Upper Canada</em>. Wikipedia.<br>
</li>
<li><em>Upper Canada</em>. Wikipedia.<br>
</li>
<li>Venne, Sharon Helen. “Settling the Fisheries: Pre-Confederation Crown Policy in Upper Canada and the Supreme Court’s decisions in R. v. NIKAL and LEWIS.” <em>Revue générale de droit</em> 31:1 (2001): 133–164.<br>
</li>
<li>Von Gernet, Alexander. “Proximity, Family Lore, and False Claims to an Algonquin Identity.” <em>Genealogy</em> 8:4 (2024): 125.<br>
</li>
<li>White, Richard. <em>The Middle Ground: Indians, Empires, and Republics in the Great Lakes Region, 1650-1815</em>. Cambridge University Press, 1991. (Influential secondary source relevant to context).<br>
</li>
<li>Williams Treaties.<br>
</li>
<li>Willes, Frances Mary. <em>A study to examine the boundary expansions of Kingston from a legal and land perspective, with emphasis on the 1998 amalgamation</em>. Masters Thesis, Queen’s University, 2014.<br>
</li>
<li>Winchell, N. H. <em>The Aborigines of Minnesota</em>. Minnesota Historical Society, 1911.</li>
</ul>
<section id="works-cited" class="level4">
<h4 class="anchored" data-anchor-id="works-cited"><strong>Works cited</strong></h4>
<p>1. www.tanakiwin.com, http://www.tanakiwin.com/wp-system/uploads/2013/10/f-Algonquin-Petition-of-June-6-1835.pdf 2. Aboriginal Dispossession in the Emergence of a Capitalist Resource Extractive Region: The Ottawa Valley, 1800-1830s, https://cpsa-acsp.ca/papers-2009/Lawson.pdf 3. mmumbesu - Publications du gouvernement du Canada, https://publications.gc.ca/collections/collection_2018/aanc-inac/R32-474-1951-eng.pdf 4. Rebellion in Upper Canada | The Canadian Encyclopedia, https://www.thecanadianencyclopedia.ca/en/article/rebellion-in-upper-canada 5. Pre-Confederation Governors, https://www.lgontario.ca/en/history/pre-confederation-governors/ 6. Sir Francis Bond Head | The Canadian Encyclopedia, https://www.thecanadianencyclopedia.ca/en/article/sir-francis-bond-head 7. Sir Francis Bond Head, Lieutenant-Governor of Upper Canada, 1793-1875, https://recherche-collection-search.bac-lac.gc.ca/eng/home/record?app=fonandcol&amp;IdNumber=2876670 8. HEAD, Sir FRANCIS BOND - Dictionary of Canadian Biography, https://www.biographi.ca/en/bio/head_francis_bond_10E.html 9. Upper Canada Land Minute Book R - Collection search, https://recherche-collection-search.bac-lac.gc.ca/eng/Home/Record?app=fonandcol&amp;IdNumber=3815074&amp;ecopy=e008428539_01 10. Index to the Upper Canada land books: Susan Smart, general editor - FamilySearch Catalog, https://www.familysearch.org/search/catalog/1022038 11. Ontario from the Trent south of the Waters’of the Rice Lake, to - Publications du gouvernement du Canada, https://publications.gc.ca/collections/collection_2018/aanc-inac/R32-488-1986-eng.pdf 12. Crawford Purchase - Wikipedia, https://en.wikipedia.org/wiki/Crawford_Purchase 13. The Crawford ‘Purchases’ - Anishinabek News, https://anishinabeknews.ca/2021/11/03/the-crawford-purchases/ 14. The report of the Pennefather Commission : Indian conditions and …, https://publications.gc.ca/collections/collection_2018/aanc-inac/R32-487-1983-eng.pdf 15. “An equitable right to be compensated”: The Dispossession of the Aboriginal Peoples of Quebec and the Emergence of a New Legal Rationale (1760–1860) - ResearchGate, https://www.researchgate.net/publication/262413116_An_equitable_right_to_be_compensated_The_Dispossession_of_the_Aboriginal_Peoples_of_Quebec_and_the_Emergence_of_a_New_Legal_Rationale_1760-1860 16. Joan Holmes &amp; Associates Inc: Home, https://joanholmes.ca/ 17. Report on the Algonquins of Golden Lake claim / Prepared by Joan Holmes &amp; Associates, Inc.&nbsp;for Ontario Native Affairs Secretariat.: R32-492/1993E-PDF, https://publications.gc.ca/site/eng/9.853164/publication.html?wbdisable=true 18. History of the Algonquins, http://www.tanakiwin.com/wp-system/uploads/2013/10/a-History-of-the-Algonquins.pdf 19. Our Proud History - Algonquins of Ontario, https://www.tanakiwin.com/algonquins-of-ontario/our-proud-history/ 20. Algonquin Territory - Canada’s History, https://www.canadashistory.ca/explore/politics-law/algonquin-territory 21. Algonquin people - Wikipedia, https://en.wikipedia.org/wiki/Algonquin_people 22. Algonquin History in The Ottawa River Watershed | PDF - Scribd, https://www.scribd.com/document/281185399/Algonquin-History-in-the-Ottawa-River-Watershed 23. 2.3 Algonquin History in the Ottawa River Watershed, https://ottawariver.org/pdf/05-ch2-3.pdf 24. L’Isle-aux-Allumettes - Wikipedia, https://en.wikipedia.org/wiki/L%27Isle-aux-Allumettes 25. History of Pontiac Ouest, https://pontiacouest.ca/en/pontiac-ouest/history-of-the-pontiac/ 26. History of the Pontiac, https://mrcpontiac.qc.ca/en/mrc/history-of-the-pontiac/ 27. 2.4 Exploration Along the Ottawa River, https://ottawariver.org/pdf/06-ch2-4.pdf 28. Sir John A. Macdonald’s Influence on the - bac-lac.gc.ca, https://dam-oclc.bac-lac.gc.ca/download?is_thesis=1&amp;oclc_number=1295222574&amp;id=4a8cf14c-814b-494a-8221-17d1b9d94588&amp;fileName=Taekema_Sarah_MA_2020.pdf 29. Land Surrenders in Ontario 1763-1867, https://publications.gc.ca/collections/collection_2017/aanc-inac/R5-350-1983-eng.pdf 30. Algonquin Petition of 1847, http://www.tanakiwin.com/wp-system/uploads/2013/10/g-Algonquin-Petition-of-1847.pdf 31. The Lieutenant-Governors of Upper Canada and Ontario 1792-1899, by D. B. Read, https://gutenberg.ca/ebooks/readdb-lieutenantgovernors/readdb-lieutenantgovernors-00-h-dir/readdb-lieutenantgovernors-00-h.html 32. List of colonial governors in 1836, https://wikipedia.nucleos.com/viewer/wikipedia_en_all/A/List_of_colonial_governors_in_1836 33. Upper Canada - Wikipedia, https://en.wikipedia.org/wiki/Upper_Canada 34. History of Toronto and County of York, Ontario, https://dn790000.ca.archive.org/0/items/historyoftoronto01mulvuoft/historyoftoronto01mulvuoft.pdf 35. 12th Parliament of Upper Canada - Wikipedia, https://en.wikipedia.org/wiki/12th_Parliament_of_Upper_Canada 36. Struggle and Story: Canada in Print - Thomas Fisher Rare Book Library - University of Toronto, https://fisher.library.utoronto.ca/sites/default/public/Canada%20150%20catalogue.pdf 37. Crawford Purchase | The Canadian Encyclopedia, https://encyclopediecanadienne.com/en/article/crawford-purchase 38. Map of Ontario treaties and reserves, https://www.ontario.ca/page/map-ontario-treaties-and-reserves 39. British-Canada’s Land Purchases, 1783-1788 - Érudit, https://www.erudit.org/fr/revues/onhistory/2019-v111-n1-onhistory04604/1059965ar.pdf 40. caid.ca, https://caid.ca/BagotRep1845.pdf 41. Bagot Report, https://dev.nctr.ca/wp-content/uploads/2021/01/Bagot-report.pdf 42. Colonial Expansion into Lanark &amp; Frontenac Counties: The petitions of Chief Pierre Shawinipinessi, https://lanarkcountyneighbours.ca/local-stories/shawinipinessi-petitions/ 43. “LAND OF WHICH THE SAVAGES STOOD IN N O PARTICULAR NEED” : DISPOSSESSING THE ALGONQUINS OF SOUTH- EASTERN ONTARIO OF T, https://www.collectionscanada.gc.ca/obj/s4/f2/dsk3/ftp05/MQ55912.pdf 44. Submission to the Algonquins of Ontario Tribunal in Consideration of the Inclusion of Thomas St.&nbsp;Jean dit Lagarde and Sophie, https://www.tanakiwin.com/wp-system/uploads/2023/02/Document-3-Initial-Submissions-made-by-L.-Clouthier-on-behalf-of-Lagarde_Carriere-line.pdf 45. MAKING MAGICAL CONNECTIONS: With Indigenous History - - Burning Passions Theatre, https://bptheatre.ca/making-magical-connections-with-perths-history/ 46. Stage 3 Archaeological Assessment Kashwakamak Lake Dam - Mississippi Valley Conservation Authority, https://mvc.on.ca/wp-content/uploads/2024/10/Stage-3-AA-Kashwakamak-Lake-Dam_.pdf 47. Enrolment Team Qualifications – Summary - Algonquins of Ontario, https://www.tanakiwin.com/wp-system/uploads/2023/06/Document-13-Information-on-JHA-Enrolment-Team.pdf 48. Technical Advisory Group - Algonquins of Ontario, https://www.tanakiwin.com/algonquins-of-ontario/technical-advisory-group/ 49. The Algonquin Land Claim - FOCA, https://foca.on.ca/wp-content/uploads/2015/06/AlgonquinNegotiationsOct2016.pdf 50. Commissions of Inquiry into Indian affairs in the Canadas, 1828-1858, https://publications.gc.ca/collections/collection_2017/aanc-inac/R5-273-1985-eng.pdf 51. REPORT - solon.org, https://www.solon.org/Aboriginal/Canada/1845_bagot_e.pdf 52. HISTORY OF THE Settlement of Upper Canada, (ONTARIO,) WITH SPECIAL REFERENCE TO THE BAY QUINTÉ. - Project Gutenberg, https://www.gutenberg.org/files/54554/54554-h/54554-h.htm 53. volume 5, https://publications.gc.ca/collections/collection_2018/aanc-inac/R32-492-1993-2-eng.pdf 54. Portraits: Canada, 1835-1838 - Nelson Cook, https://nelsoncook.com/canada%3A-1835-1838 55. - 3 - ONTARIO HISTORICAL SOCIETY PAPER AND RECORDS and ONTARIO HISTORY Section 1 Table of Contents Volume 1 to Volume 64 Volume, https://ontariohistoricalsociety.ca/wp-content/uploads/2018/08/OH_INDEX_Part_1_-_Section_1_-_Table_of_Contents.pdf 56. Head, Francis Bond, Sir, 1793-1875 - The Online Books Page, https://onlinebooks.library.upenn.edu/webbin/book/lookupname?key=Head%2C%20Francis%20Bond%2C%20Sir%2C%201793%2D1875 57. Report Regarding Ancestor Thomas Lagarde dit St.&nbsp;Jean (RIN #11565) - Algonquins of Ontario, https://www.tanakiwin.com/wp-system/uploads/2022/12/Document1-Enrolment-Officers-Report-Regarding-Ancestor-Thomas-Lagarde-dit-St-Jean.pdf 58. MATTAWA NIPISSING MÉTIS HISTORICAL RESEARCH PROJECT FINAL SYNTHESIS REPORT - Metis Nation of Ontario, https://www.metisnation.org/wp-content/uploads/2011/07/final20synthesis20report20may20520kh.pdf 59. HILLIER, GEORGE – Dictionary of Canadian Biography, https://www.biographi.ca/en/bio/hillier_george_7E.html 60. OFT E ARCHIVES OF ONTARIO., VOW ME TWO-. - The Loyalist Collection, https://loyalist.lib.unb.ca/sites/default/files/Guide%20to%20the%20Holdings%20of%20the%20Archives%20of%20Ontario%20Volume%20Two.pdf 61. Kingston: the Crawford Purchase - Aboriginal Law &amp; Indigenous Laws - Research Guides, https://guides.library.queensu.ca/Aboriginal-and-Indigenous-law/kingston-crawford-purchase 62. List of governors general of Canada - Wikipedia, https://en.wikipedia.org/wiki/List_of_governors_general_of_Canada 63. Maamwi Treaties of Ontario Database, https://tlp-lpa.ca/az.php 64. The Ottawa River By Night - KICHI SIBI, https://ottawariver.org/pdf/0-ORHDC.pdf 65. The Project Gutenberg eBook of The Jesuits in North America by Francis Parkman, https://www.gutenberg.org/ebooks/6933.html.images 66. STAGE 1 AND 2 ARCHAEOLOGICAL ASSESSMENTS FOR A PROPOSED SEVERANCE 254 LAKE AVENUE WEST PART LOT 13, CONCESSION 11 GEOGRAPHIC - Lanark County, https://www.lanarkcounty.ca/en/doing-business/resources/documents/Planning/254-Lake-Ave-W/Submission/06-Archaeology—Past-Recovery.pdf 67. Upper Canada. Lieutenant-Governor (1836-1838 : Head) - Toronto Public Library Archive, https://digitalarchivetest.emuseum.com/people/59234/upper-canada-lieutenantgovernor-18361838–head/objects 68. Lieutenant Governor Sir Francis Bond Head - Collection search, https://recherche-collection-search.bac-lac.gc.ca/eng/home/record?idnumber=3133001&amp;app=FonAndCol 69. R32-325-1985-eng.pdf, https://publications.gc.ca/collections/collection_2018/aanc-inac/R32-325-1985-eng.pdf 70. State minute books of the Executive Council of Upper Canada : C-98 - Canadiana Heritage, https://heritage.canadiana.ca/view/oocihm.lac_reel_c98 71. Treaty 19 - GRASAC - University of Toronto, https://grasac.artsci.utoronto.ca/?p=2215 72. THE MISSISSAUGAS BETWEEN TWO WORLDS: STRATEGIC ADJUSTMENTS TO CHANGING LANDSCAPES OF POWER, https://cjns.brandonu.ca/wp-content/uploads/17-2-cjnsv17no2_pg259-292.pdf 73. Polishing and Tarnishing the Chain: An Examination of Mississauga Treaties around the Head of Lake Ontario, 1780-1820 - The Atrium, https://atrium.lib.uoguelph.ca/bitstreams/8a8789fb-0d00-4b01-b50d-2e229f2eba6c/download 74. Treaty Texts - Upper Canada Land Surrenders, https://www.rcaanc-cirnac.gc.ca/eng/1370372152585/1581293792285 75. Upper Canada Land Surrenders and the Williams Treaties (1764-1862/1923), https://www.rcaanc-cirnac.gc.ca/eng/1360941656761/1544619778887 76. Great Lakes Treaty Timeline - GRASAC, https://grasac.artsci.utoronto.ca/?page_id=1324 77. Settling the Fisheries: Pre-Confederation Crown Policy in Upper Canada and the Supreme Court’s decisions in R. v. - Érudit, https://www.erudit.org/en/journals/rgd/2001-v31-n1-rgd01629/1027786ar.pdf 78. Proximity, Family Lore, and False Claims to an Algonquin Identity - MDPI, https://www.mdpi.com/2313-5778/8/4/125 79. Ethnohistory of Algonkian Speaking People of Georgian Bay. - MacSphere, https://macsphere.mcmaster.ca/bitstream/11375/13929/1/fulltext.pdf</p>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp("https:\/\/jburnford\.github\.io\/intro_llms_for_historians\/");
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>